version: 2
sources:
  - name: staging  # Called inside Jinja Block
    database: de-zoomcamp-400010  #  BigQuery Project Name
    schema: trip_data_all  # BigQuery Dataset Name
    tables:
      - name: green_tripdata
      - name: yellow_tripdata